import type { CommandSpec } from './command-spec.js';
import { CommandSpecError } from './errors.js';

const ALL_DISTRIBUTIONS = ['debian', 'rhel', 'alpine', 'unknown'] as const;

export const COMMAND_CATALOG = [
  command('permission.uid', 'id', ['-u']),
  command('permission.user', 'id', ['-un']),
  command('permission.groups', 'id', ['-Gn']),
  command('permission.sudo', 'sudo', ['-n', '--', 'true']),
  command('host.uname', 'uname', ['-a']),
  command('host.kernel-release', 'uname', ['-r']),
  command('host.architecture', 'uname', ['-m']),
  command('host.os-release', 'cat', ['/etc/os-release']),
  command('host.hostname', 'hostname', []),
  command('host.hostname-fqdn', 'hostname', ['-f']),
  command('host.timezone', 'timedatectl', ['show', '--property=Timezone', '--value', '--no-pager']),
  command('host.timezone-file', 'cat', ['/etc/timezone']),
  command('host.timezone-link', 'readlink', ['-f', '/etc/localtime']),
  command('host.uptime', 'cat', ['/proc/uptime']),
  command('host.virtualization', 'systemd-detect-virt', []),
  command('host.virtualization-dmi', 'cat', ['/sys/class/dmi/id/product_name']),
  command('host.lscpu', 'lscpu', ['-J']),
  command('host.lscpu-text', 'lscpu', []),
  command('host.cpuinfo', 'cat', ['/proc/cpuinfo']),
  command('host.memory', 'cat', ['/proc/meminfo']),
  command('storage.lsblk', 'lsblk', ['-J', '-b', '-O']),
  command('storage.lsblk-basic', 'lsblk', ['-J', '-b']),
  command('storage.lsblk-pairs', 'lsblk', [
    '-P',
    '-b',
    '-o',
    'NAME,KNAME,PATH,TYPE,SIZE,PKNAME,FSTYPE,UUID,MOUNTPOINT,MODEL,SERIAL,ROTA,RM',
  ]),
  command('storage.findmnt', 'findmnt', ['-J']),
  command('storage.mountinfo', 'cat', ['/proc/self/mountinfo']),
  command('storage.df-bytes', 'df', ['-B1', '-P']),
  command('storage.df-kilobytes', 'df', ['-k', '-P']),
  command('storage.df-inodes', 'df', ['-i', '-P']),
  command('storage.fstab', 'cat', ['/etc/fstab']),
  command('storage.swap', 'swapon', [
    '--show=NAME,TYPE,SIZE,USED,PRIO',
    '--bytes',
    '--noheadings',
    '--raw',
  ]),
  command('storage.swap-proc', 'cat', ['/proc/swaps']),
  command('network.addresses', 'ip', ['-j', 'addr']),
  command('network.addresses-text', 'ip', ['-o', 'addr', 'show']),
  command('network.routes', 'ip', ['-j', 'route']),
  command('network.routes-text', 'ip', ['route', 'show', 'table', 'main']),
  command('network.dns', 'cat', ['/etc/resolv.conf']),
  command('firewall.firewalld', 'firewall-cmd', ['--state'], {
    maxOutputBytes: 100_000,
    sudo: 'allowed',
  }),
  command('firewall.ufw', 'ufw', ['status'], { maxOutputBytes: 500_000, sudo: 'allowed' }),
  command('firewall.nft', 'nft', ['-j', 'list', 'ruleset'], {
    maxOutputBytes: 1_000_000,
    sudo: 'allowed',
  }),
  command('firewall.iptables', 'iptables-save', [], {
    maxOutputBytes: 1_000_000,
    sudo: 'allowed',
  }),
  command('environment.dpkg', 'dpkg-query', ['--version'], { maxOutputBytes: 100_000 }),
  command('environment.rpm', 'rpm', ['--version'], { maxOutputBytes: 100_000 }),
  command('environment.apk', 'apk', ['--version'], { maxOutputBytes: 100_000 }),
  command(
    'process.list',
    'ps',
    ['-ww', '-eo', 'pid=,ppid=,uid=,etimes=,cgroup:512=,args=', '--no-headers'],
    {
      maxOutputBytes: 10_000_000,
    },
  ),
  command(
    'process.links',
    'find',
    [
      '/proc',
      '-mindepth',
      '2',
      '-maxdepth',
      '2',
      '-type',
      'l',
      '(',
      '-name',
      'exe',
      '-o',
      '-name',
      'cwd',
      ')',
      '-printf',
      '%p\\t%l\\n',
    ],
    { maxOutputBytes: 10_000_000, sudo: 'allowed' },
  ),
  command('process.passwd', 'cat', ['/etc/passwd'], { maxOutputBytes: 1_000_000 }),
  command('network.sockets', 'ss', ['-H', '-lntup'], { sudo: 'allowed' }),
  command('network.sockets-netstat', 'netstat', ['-lntup'], { sudo: 'allowed' }),
  command('service.systemd-units', 'systemctl', [
    'list-units',
    '--type=service',
    '--all',
    '--no-pager',
    '--plain',
    '--no-legend',
  ]),
  command('service.systemd-files', 'systemctl', [
    'list-unit-files',
    '--type=service',
    '--no-pager',
    '--plain',
    '--no-legend',
  ]),
  command(
    'service.systemd-details',
    'systemctl',
    [
      'show',
      '*.service',
      '--all',
      '--no-pager',
      '--property=Id',
      '--property=Description',
      '--property=LoadState',
      '--property=ActiveState',
      '--property=SubState',
      '--property=UnitFileState',
      '--property=MainPID',
      '--property=FragmentPath',
      '--property=WorkingDirectory',
      '--property=ExecStart',
      '--property=ExecReload',
      '--property=EnvironmentFiles',
      '--property=User',
      '--property=Group',
    ],
    { maxOutputBytes: 10_000_000 },
  ),
  {
    arguments: [
      { literal: 'show' },
      { parameter: 'unitName' },
      { literal: '--all' },
      { literal: '--no-pager' },
      { literal: '--property=Id' },
      { literal: '--property=Description' },
      { literal: '--property=LoadState' },
      { literal: '--property=ActiveState' },
      { literal: '--property=SubState' },
      { literal: '--property=UnitFileState' },
      { literal: '--property=MainPID' },
      { literal: '--property=FragmentPath' },
      { literal: '--property=WorkingDirectory' },
      { literal: '--property=ExecStart' },
      { literal: '--property=ExecReload' },
      { literal: '--property=EnvironmentFiles' },
      { literal: '--property=User' },
      { literal: '--property=Group' },
    ],
    executable: 'systemctl',
    id: 'service.systemd-show',
    maxOutputBytes: 500_000,
    parameters: {
      unitName: {
        kind: 'string',
        maxLength: 256,
        pattern: /^[A-Za-z0-9_.@:\\-]+\.service$/,
      },
    },
    requiredCommands: ['systemctl'],
    sudo: 'never',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 15_000,
  },
  {
    arguments: [
      { literal: '-p' },
      { parameter: 'pid' },
      { literal: '-o' },
      { literal: 'pid=,ppid=,user=,etimes=,args=' },
    ],
    executable: 'ps',
    id: 'runtime.process-details',
    maxOutputBytes: 500_000,
    parameters: {
      pid: { kind: 'integer', max: 4_194_304, min: 1 },
    },
    requiredCommands: ['ps'],
    sudo: 'never',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 15_000,
  },
  {
    arguments: [{ parameter: 'path' }],
    executable: 'cat',
    id: 'runtime.process-cgroup',
    maxOutputBytes: 100_000,
    parameters: {
      path: { kind: 'path', maxLength: 64, pattern: /^\/proc\/[0-9]+\/cgroup$/ },
    },
    requiredCommands: ['cat'],
    sudo: 'never',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 15_000,
  },
  command('docker.ps', 'docker', ['ps', '-a', '--no-trunc', '--format', '{{json .}}'], {
    maxOutputBytes: 5_000_000,
    sudo: 'allowed',
  }),
  command(
    'docker.ps-basic',
    'docker',
    ['ps', '-a', '--no-trunc', '--format', '{{.ID}}\t{{.Names}}\t{{.Image}}\t{{.State}}'],
    {
      maxOutputBytes: 5_000_000,
      sudo: 'allowed',
      timeoutMs: 10_000,
    },
  ),
  command('docker.info', 'docker', ['info', '--format', '{{json .}}'], {
    maxOutputBytes: 1_000_000,
    sudo: 'allowed',
  }),
  {
    arguments: [{ literal: 'inspect' }, { parameter: 'containerId' }],
    executable: 'docker',
    id: 'docker.inspect',
    maxOutputBytes: 5_000_000,
    parameters: {
      containerId: { kind: 'string', maxLength: 64, pattern: /^[a-fA-F0-9]{12,64}$/ },
    },
    requiredCommands: ['docker'],
    sudo: 'allowed',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 30_000,
  },
  command('docker.compose-ls', 'docker', ['compose', 'ls', '--all', '--format', 'json'], {
    maxOutputBytes: 1_000_000,
    sudo: 'allowed',
  }),
  command('docker-compose.ls', 'docker-compose', ['ls', '--all', '--format', 'json'], {
    maxOutputBytes: 1_000_000,
    sudo: 'allowed',
  }),
  directoryScanCommand('directory.scan', true, false),
  directoryScanCommand('directory.scan-cross-filesystems', false, false),
  directoryScanCommand('directory.scan-stat', true, true),
  directoryScanCommand('directory.scan-stat-cross-filesystems', false, true),
  {
    arguments: [{ parameter: 'path' }],
    executable: 'cat',
    id: 'directory.read-config',
    maxOutputBytes: 5_000_000,
    parameters: {
      path: { kind: 'path', maxLength: 4096 },
    },
    requiredCommands: ['cat'],
    sudo: 'allowed',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 10_000,
  },
  {
    arguments: [
      { literal: '--printf' },
      { literal: '%F\t%s\t%U\t%G\t%a\t%Y\t%n\\n' },
      { parameter: 'path' },
    ],
    executable: 'stat',
    id: 'directory.stat',
    maxOutputBytes: 1_000_000,
    parameters: {
      path: { kind: 'path', maxLength: 4096 },
    },
    requiredCommands: ['stat'],
    sudo: 'allowed',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 15_000,
  },
  {
    arguments: [
      { literal: '-c' },
      { literal: '%F\t%s\t%U\t%G\t%a\t%Y\t%n' },
      { parameter: 'path' },
    ],
    executable: 'stat',
    id: 'directory.stat-basic',
    maxOutputBytes: 1_000_000,
    parameters: {
      path: { kind: 'path', maxLength: 4096 },
    },
    requiredCommands: ['stat'],
    sudo: 'allowed',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 15_000,
  },
  {
    arguments: [
      { parameter: 'searchRoot' },
      { literal: '-xdev' },
      { literal: '-mindepth' },
      { literal: '1' },
      { literal: '-maxdepth' },
      { parameter: 'maxDepth' },
      { literal: '-iname' },
      { parameter: 'searchTerm' },
      { literal: '-printf' },
      { literal: '%y\t%s\t%u\t%g\t%m\t%T@\t%p\t%l\\n' },
    ],
    executable: 'find',
    id: 'directory.search-name',
    maxOutputBytes: 2_000_000,
    parameters: {
      maxDepth: { kind: 'integer', min: 1, max: 8 },
      searchRoot: { kind: 'path', maxLength: 4096 },
      searchTerm: { kind: 'string', maxLength: 128, pattern: /^\*[A-Za-z0-9][A-Za-z0-9._@-]*\*$/ },
    },
    requiredCommands: ['find'],
    sudo: 'allowed',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 15_000,
  },
] as const satisfies readonly CommandSpec[];

const COMMANDS_BY_ID = new Map(COMMAND_CATALOG.map((spec) => [spec.id, spec]));

export function getCommandSpec(id: string): CommandSpec {
  const spec = COMMANDS_BY_ID.get(id);
  if (spec === undefined) {
    throw new CommandSpecError('COMMAND_NOT_ALLOWED', `Command '${id}' is not in the allowlist.`);
  }
  return spec;
}

function command(
  id: string,
  executable: string,
  args: readonly string[],
  overrides: Partial<Pick<CommandSpec, 'maxOutputBytes' | 'sudo' | 'timeoutMs'>> = {},
): CommandSpec {
  return {
    arguments: args.map((literal) => ({ literal })),
    executable,
    id,
    maxOutputBytes: overrides.maxOutputBytes ?? 5_000_000,
    parameters: {},
    requiredCommands: executable === 'sudo' ? ['sudo', 'true'] : [executable],
    sudo: overrides.sudo ?? 'never',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: overrides.timeoutMs ?? 30_000,
  };
}

function directoryScanCommand(
  id: string,
  sameFileSystem: boolean,
  statFallback: boolean,
): CommandSpec {
  const arguments_: Array<{ literal: string } | { parameter: string }> = [
    { parameter: 'path' },
    ...(sameFileSystem ? [{ literal: '-xdev' }] : []),
    { literal: '-mindepth' },
    { literal: '0' },
    { literal: '-maxdepth' },
    { parameter: 'maxDepth' },
    { literal: '(' },
    { literal: '-type' },
    { literal: 'd' },
    { literal: '(' },
    { literal: '-name' },
    { literal: '.git' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'node_modules' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'vendor' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: '.cache' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'cache' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'overlay' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'overlay2' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'pg_wal' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: 'pg_xact' },
    { literal: '-o' },
    { literal: '-name' },
    { literal: '#innodb_redo' },
    { literal: ')' },
    { literal: '-prune' },
    { literal: ')' },
    { literal: '-o' },
  ];
  if (statFallback) {
    arguments_.push(
      { literal: '-exec' },
      { literal: 'stat' },
      { literal: '-c' },
      { literal: '%F\t%s\t%U\t%G\t%a\t%Y\t%n' },
      { literal: '{}' },
      { literal: '+' },
    );
  } else {
    arguments_.push({ literal: '-printf' }, { literal: '%y\t%s\t%u\t%g\t%m\t%T@\t%p\t%l\\n' });
  }
  return {
    arguments: arguments_,
    executable: 'find',
    id,
    maxOutputBytes: 10_000_000,
    parameters: {
      maxDepth: { kind: 'integer', min: 1, max: 20 },
      path: { kind: 'path', maxLength: 4096 },
    },
    requiredCommands: statFallback ? ['find', 'stat'] : ['find'],
    sudo: 'allowed',
    supportedDistributions: ALL_DISTRIBUTIONS,
    timeoutMs: 30_000,
  };
}
